### ISSUE TITLE
safari support

### ISSUE THREAD

**Issue by gracielaPosadas** [akzhy/Vara#10]
I tested this in safari and is not working any advice for support in that browser

**Comment by akzhy** [comment]
Hi,
Can you check for any console errors, and are you testing one of the demos provided or are you testing with your code ?

If you are testing with your own code, can you try one of the demos on Safari and see if they are working ?

**Comment by gracielaPosadas** [comment]
Hih, thanks for the response is not any error console.  But even the main page (http://vara.akzhy.com/) when I open it in safari is not showing any text( hello there ...) 

I try to animate and show he svg via CSS 
  <style>
        path {
            animation: dash 5s linear forwards;
            -webkit-animation: dash 5s linear forwards;
        }
        @keyframes dash {
       to {
          stroke-dashoffset: 0;
       }
     }
    </style> 
But also it did not work

**Comment by akzhy** [comment]
That is a strange issue. I will test this on Safari and will try to fix it tomorrow.

**Comment by akzhy** [comment]
Hi, this issue has been fixed. Try it out and if you find anything new feel free to raise another issue or comment it here.

#11
