### ISSUE TITLE
Is it possible to make an image/svg follow the stroke path ?

### ISSUE THREAD

**Issue by yolossn** [akzhy/Vara#19]
Great work 👏.  I am looking to create a text animation where an image of a pen or a chalk follows the stroke path. Wanted to know if it is possible to achieve the same with vara.
![out](https://user-images.githubusercontent.com/22731013/97079493-04c25880-1612-11eb-92f4-da2d654ae422.gif)

**Comment by akzhy** [comment]
Hey, @yolossn this is something that I've been also trying, but so far I couldn't make it work.
The two possible methods are 


1. Us animatemotion and move an object along the path
2. Manually calculate the position of the current point and place the object at that point

Both these options failed for me when I tried it, but i will see if there are any alternative ways.
