### ISSUE TITLE
Character F draw 7 for all fonts

### ISSUE THREAD

**Issue by dsahani-dev** [akzhy/Vara#20]
I found it very interesting but somehow F character is drawing 7.

**Comment by akzhy** [comment]
Hey @dsahani-dev sorry for the delay in response. I can't reproduce this issue. Which font did you use/ Can you provide a demo?

**Comment by dsahani-dev** [comment]
Thanks for reply @akzhy,
I am using your example itself
https://codepen.io/akzhy/pen/YdbYbj
Please check the attached file for more details:
![vara](https://user-images.githubusercontent.com/62604016/100854071-85486480-34ae-11eb-9d28-81ec9660f044.PNG)
Thanks,

**Comment by akzhy** [comment]
Hey @dsahani-dev  The font I used is made from the font Satisfy available on Google Fonts. F is like that in the font 
![image](https://user-images.githubusercontent.com/20243910/100858901-93997f00-34b4-11eb-8be9-82251fa68148.png) So it's a feature. not a bug 😅

**Comment by dsahani-dev** [comment]
Hahaha got it, thanks for your help.
