### ISSUE TITLE
Font Update

### ISSUE THREAD

**Issue by xFeXx** [akzhy/Vara#21]
As I couldn't create a new pull request, here are updated Files for Shadows Into Light, which include umlauts.
[ShadowIntoLightUmlauts.zip](https://github.com/akzhy/Vara/files/6800340/ShadowIntoLightUmlauts.zip)

**Comment by akzhy** [comment]
Hey,
Thanks for this, I've been busy and was not able to take a look. I will add this to the list by the weekend.

**Comment by akzhy** [comment]
Hey, I just tested this and there seems to be some issues with the line-height. This might be related to the font generator. So I will include this as part of [version 2](https://github.com/akzhy/Vara/tree/v2.0.0) which will have an updated better font generator.
