### ISSUE TITLE
appenChild problem 

### ISSUE THREAD

**Issue by Knight-Fiury** [akzhy/Vara#22]
![Screenshot_20210915-000806](https://user-images.githubusercontent.com/86944710/133310719-494fe8b6-41f3-47d9-92e3-7878817d20e5.png)

hi
i am having this problem.... plz help me..

**Comment by akzhy** [comment]
Hey, sorry for the delay in response. I think issue is because the element you provided doesn't exist in the DOM.

```
new Vara("#element","font.json",[{
	text:"Handwritten"
}],{
	fontSize:46
});
```

If you are using the above structure make sure an element with id `#element` is available in the DOM when `Vara` is invoked.
