### ISSUE TITLE
[Feature] add per character configuration

### ISSUE THREAD

**Issue by wdfinch** [akzhy/Vara#37]
I was wondering if it would be possible to add the ability to configure settings on individual characters rather than the entire text string. I'd like to adjust the spacing between certain characters for my specific use case.

For example, in the Parisienne font, some letters are too far from others because they have a long tail or hat. I've attached an example below. In this example, the capital **F** has a wide top; therefore, the lowercase **r** is very far away. I'd like to move it closer. 

![Screenshot from 2023-03-20 17-17-51](https://user-images.githubusercontent.com/36898266/226492469-d567a2be-0801-4d09-b886-d34be7f29528.png)

**Comment by akzhy** [comment]
Hey, you can use the `letterSpacing` property to fix this.

```
letterSpacing: {
  'F': -4,
  global: -1
}
```

**Comment by wdfinch** [comment]
Thanks so much! This is exactly what I needed. I see it now in the docs. 

One limitation here is you need to adjust the spacing for every character globally instead of individual characters. For example, if I have multiple uppercase 'F' letters, I might want to adjust the spacing for each one individually depending on the other letters near them. So maybe something like this would give more control:

```
letterSpacing: {
    'F': [{
            index: 0,
            spacing: -4
        },
        {
            index: 4,
            spacing: 10
        }
    ],
    global: -1
}
```
