### ISSUE TITLE
Animation instantly ends

### ISSUE THREAD

**Issue by egold555** [akzhy/Vara#6]
Hello! For the life of me I can not figure this out. I am not sure if this is a bug or I am just doing something wrong, but when ever I try to manually start a animation, no animation plays and the animationEnd function is called immediately.

Basically what I am trying to do, is at a certain point in time, I can tell Vara to play the animation, then it goes through and plays through all the text block animations in order.

Here is the code I have so far:

```javascript

$(document).ready(function () {

    var vara = new Vara("#vara-container", "PacificoSLO.json", [{
            text: "Hello!",
            y: 50,
            duration: 1000,
            id: "t1",
            autoAnimation: false,
            queued: true,
        },
        {
            text: "Use the Wii remote to control me!",
            id:"t2",
            queued: true,
            autoAnimation: false,
        },
        {
            text: "Hold down the back button to draw.",
            id:"t3",
            queued: true,
            autoAnimation: false,
        },
        {
            text: "The A button resets your drawing.",
            id:"t4",
            queued: true,
            autoAnimation: false,
        },
        {
            text: "(Move remote to dismiss)",
            id:"t5",
            queued: true,
            autoAnimation: false,
        }
        ], {
        fontSize: 70,
        color: "white",
        strokeWidth: 2,
        textAlign: "center",
        duration: 7000,
        width: 1200,
    });
    

    vara.animationEnd(function(i, o) {
        console.log("Animation End " + i);
    });
    
    vara.ready(function(){
        vara.draw("t1");
        console.log("vara is ready");
    });

});

```

Any help is appreciated.

-- Eric

**Comment by akzhy** [comment]
Hi,
This is definitely a bug, I will fix it as soon as i can.
Meanwhile if you are trying to start the animation after an event or something, you can try the `playAll()` method. It will animate all the text blocks obeying delay and queue. 
I have made a  fiddle to demonstrate it https://jsfiddle.net/akzhy/8hvoyr9q/7/

**Comment by egold555** [comment]
Thanks for the fast reply! The 'playAll()' function did the trick.
