### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by Chnapy** [akzhy/Vara#9]
Hi,

I'm writing typescript typings of Vara, and I was asking myself how you want these typings to be added to the project.

I can do a pull request with a `index.d.ts` file.
Or I can add the typings to the Definitely Typed (so they would be accessible from `@types/vara`).

Pro / Cons of each solution: https://www.triplet.fi/blog/three-ways-to-provide-typescript-type-definitions-to-3rd-party-libraries/

Which do you prefer?

**Comment by akzhy** [comment]
Hi,
I am not familiar with typescript much. I am planning to learn it but as of now I have no experience with typescript. So by reading the post I believe the best option is to add it to the Definitely Typed. 
But if you feel an index.d.ts is the better option, do create a pull request with it.

**Comment by Chnapy** [comment]
I made a PR to the Definitely Typed => https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33748
If there checks & review are OK it should be accessible soon from `@types/vara` :+1:
